name: Ruby Conformance CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.5", "2.6", "2.7", "3.0", "3.1"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Bundle install
      run: 'bundle install'
    - name: Run HTTP conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v1.4.1
      with:
        functionType: 'http'
        useBuildpacks: false
        cmd: "'bundle exec functions-framework-ruby --source test/conformance/app.rb --target http_func --signature-type http'"
    - name: Run CloudEvent conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v1.4.1
      with:
        functionType: 'cloudevent'
        useBuildpacks: false
        validateMapping: true
        cmd: "'bundle exec functions-framework-ruby --source test/conformance/app.rb --target cloudevent_func --signature-type cloudevent'"
    - name: Run HTTP concurrency conformance test
      uses: GoogleCloudPlatform/functions-framework-conformance/action@4f37e559575e4770aad085cde8ac0b65b85e9036
      with:
        version: '4f37e559575e4770aad085cde8ac0b65b85e9036'
        functionType: 'http'
        useBuildpacks: false
        validateConcurrency: true
        cmd: "'bundle exec functions-framework-ruby --source test/conformance/app.rb --target concurrenct_func"
