name: Ruby Conformance CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.5", "2.6", "2.7", "3.0", "3.1"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Bundle install
      run: 'bundle install'
    - name: Run it
      run: ./client -buildpacks=false -builder-source=test/conformance -type=http -validate-concurrency=true -cmd='bundle exec functions-framework-ruby --source test/conformance/app.rb --target concurrent_func --signature-type http'
